### ISSUE TITLE
Explainable Text

### ISSUE THREAD

**Issue by giuliaass** [wangyongjie-ntu/Awesome-explainable-AI#10]
Hi,
I run a text classification problem in RStudio with Keras. I use Word Embeddings.
Now I want to explain the model globally. Do you have a tip which method I can use for this?
Thank you!

**Comment by wangyongjie-ntu** [comment]
DALEX: https://github.com/ModelOriented/DALEX 
DALEXtra: https://github.com/ModelOriented/DALEXtra
You can refer to the above two repos for some suggestions. These two are specific for the R language.
