### ISSUE TITLE
ExKMC and outliertree for explainable clustering and outlier detection

### ISSUE THREAD

**Issue by Dobatymo** [wangyongjie-ntu/Awesome-explainable-AI#14]
You could add these :)
https://github.com/david-cortes/outliertree
https://github.com/navefr/ExKMC

**Comment by wangyongjie-ntu** [comment]
@Dobatymo  
Thanks. Grad to add these two links. You are welcome to pull requests on XAI to this repo. Feel free to do it. Your contribution will count a lot. 

Warmest regards,
Yongjie
