### ISSUE TITLE
Relevant EMNLP 2024 paper

### ISSUE THREAD

**Issue by JoakimEdin** [wangyongjie-ntu/Awesome-explainable-AI#29]
Our paper [An Unsupervised Approach to Achieve Supervised-Level Explainability in Healthcare Records](https://arxiv.org/abs/2406.08958) was accepted to EMNLP 2024 main. The paper is focused on the automated medical coding task. We demonstrate that we can produce similar faithfulness and plausibility explanations as the state-of-the-art supervised method but without training on rationales/evidence spans. We achieve this feat with two approaches:
1. We propose a new explanation method: AttInGrad
2. We train our model to be adversarial robust.

We released [a repository for someone to get started on explainable medical coding](https://github.com/JoakimEdin/explainable-medical-coding/tree/main)

I have also written [a blog post about the paper](https://substack.com/home/post/p-148949862?r=3modbm&utm_campaign=post&utm_medium=web)

**Comment by wangyongjie-ntu** [comment]
@JoakimEdin Congratulations on your EMNLP work!
I have put your work in this git repo.  Without any clear definition of XAI, in recent years, many many papers about XAI have been proposed. It becomes more difficult for me to cover the latest research in this repo.  More pull requests related to XAI are highly encouraged if you are interested. Thanks.
