### ISSUE TITLE
Another list

### ISSUE THREAD

**Issue by hbaniecki** [wangyongjie-ntu/Awesome-explainable-AI#5]
Related FYI
- https://github.com/jphall663/awesome-machine-learning-interpretability
- https://github.com/lopusz/awesome-interpretable-machine-learning
- https://github.com/pbiecek/xai_resources

**Comment by wangyongjie-ntu** [comment]
Hi @hbaniecki,

Tons of thanks.  
I have added these repos at the end of Readme.md.

Yongjie
